USE airline_db;

DELETE FROM schedules;

INSERT INTO schedules (flight_id, departure_time, arrival_time, available_seats, status) VALUES
(1,  DATE_ADD(NOW(), INTERVAL 5 HOUR),   DATE_ADD(NOW(), INTERVAL 7 HOUR),   180, 'SCHEDULED'),
(2,  DATE_ADD(NOW(), INTERVAL 8 HOUR),   DATE_ADD(NOW(), INTERVAL 10 HOUR),  150, 'SCHEDULED'),
(3,  DATE_ADD(NOW(), INTERVAL 12 HOUR),  DATE_ADD(NOW(), INTERVAL 14 HOUR),  160, 'SCHEDULED'),
(4,  DATE_ADD(NOW(), INTERVAL 26 HOUR),  DATE_ADD(NOW(), INTERVAL 28 HOUR),  170, 'SCHEDULED'),
(5,  DATE_ADD(NOW(), INTERVAL 30 HOUR),  DATE_ADD(NOW(), INTERVAL 32 HOUR),  180, 'SCHEDULED'),
(6,  DATE_ADD(NOW(), INTERVAL 34 HOUR),  DATE_ADD(NOW(), INTERVAL 36 HOUR),  150, 'SCHEDULED'),
(7,  DATE_ADD(NOW(), INTERVAL 48 HOUR),  DATE_ADD(NOW(), INTERVAL 50 HOUR),  140, 'SCHEDULED'),
(8,  DATE_ADD(NOW(), INTERVAL 56 HOUR),  DATE_ADD(NOW(), INTERVAL 58 HOUR),  170, 'SCHEDULED'),
(9,  DATE_ADD(NOW(), INTERVAL 72 HOUR),  DATE_ADD(NOW(), INTERVAL 81 HOUR),  250, 'SCHEDULED'),
(10, DATE_ADD(NOW(), INTERVAL 76 HOUR),  DATE_ADD(NOW(), INTERVAL 80 HOUR),  300, 'SCHEDULED'),
(1,  DATE_ADD(NOW(), INTERVAL 96 HOUR),  DATE_ADD(NOW(), INTERVAL 98 HOUR),  180, 'SCHEDULED'),
(2,  DATE_ADD(NOW(), INTERVAL 120 HOUR), DATE_ADD(NOW(), INTERVAL 122 HOUR), 150, 'SCHEDULED'),
(3,  DATE_ADD(NOW(), INTERVAL 144 HOUR), DATE_ADD(NOW(), INTERVAL 146 HOUR), 160, 'SCHEDULED');

SELECT CONCAT('Done! Schedules refreshed: ', COUNT(*)) AS result FROM schedules;
